### ISSUE TITLE
extension does not work with circle 2.0

### ISSUE THREAD

**Issue by lancehitchcock** [jvandyke/vsc-circleci#7]
circle 2.0 introduces a {repo}/.circleci/config.yml file rather than the {repo}/circle.yml file at the root. This extension won't start because it doesn't detect the circle yaml in a 2.0 enabled repository.

**Comment by jvandyke** [comment]
@lancehitchcock Thanks to the help of some other folks, this should work now if you grab the latest version (0.5.0). Please let me know if there are still issues.

**Comment by gabe-cabral** [comment]
For me is not working yet.
